[project]
name = "firmae"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "binwalk>=2.1.0",
    "coloredlogs>=15.0.1",
    "python-magic>=0.4.27",
]
